recebido = input('Digite algo: ')

tipo_primitivo = type(recebido)
espaco = recebido.isspace()
numero = recebido.isdigit()
alfab = recebido.isalpha()
alfanum = recebido.isalnum()
maiu = recebido.isupper()
minu = recebido.islower()
capit = recebido.istitle()

print('O tipo primitivo é {}'.format(tipo_primitivo))
print('´Só tem espaços? {}'.format(espaco))
print('É um número? {}'.format(numero))
print(('É alfabético? {}'.format(alfab)))
print('É alfanumérico? {}'.format(alfanum))
print('Esta em maiúscula? {}'.format(maiu))
print('Está em minúscula? {}'.format(minu))
print('Está capitalizada? {}'.format(capit))
